a=2
b=2.7
c=20.5
d=88.8
print(type(a))
print(type(b))
print(type(c))
print(type(d))
f=a+b+c+d#2757.3
print("addition:",f)
print(type(f))
s=a-b-c
print("subtraction:")
print(type(s))
m=a*d
print("Multiplication:",m)
print(type(m))
d=c/d;
print("division:",d)
print(type(d))
div=c//d
print("Division //:",div)
print(type(div))
exp=a**b
print("Exponential:",exp)
print(type(exp))
rem=b%a
print("Remainder:",rem)
print(type(rem))
