print("")
print("              SRI GOODWILL COMUTERS")
print("____________________________________________________________")
print("           The Institute of Computers and Accounts")
print("____________________________________________________________")
print("Address: 2-257-2,Society Colony,NTR circle,Madanapalle-517325.")
print("ph: 08571-224222,9959993974,8333936767")
print("____________________________________________________________")
print("                      RECEIPT                                                            date:28/06/2025")
print("Name of the student: G.Yashitha")
print("course: ADCA,C,Python Batch No: 1152 Timing:10-4pm")
print("___________________________________________________")
print("|sl.No  |   PARTICULARS            |   AMOUNT     |")
print("|1.     |   Course Fees            |   12000      |")
print("|2.     |   Registration Fees      |   500        |")
print("|3.     |   Examination Fees       |   1500       |")
print("|4.     |   Tally Prime Exam Fees: |  0           |")
print("|5.     |   Books/others           |  120         |")
print("|_______|__________________________|______________|")
print("                              Total: 14120")
print("Rupees in words: fourteen thousand one hundred twenty ")
print("Mode of payment:")
print("cash: 2120        UPI: 12000          cheque/DD: 0")
print("Student signature:                                                    Receiver signature with stamp:")
  
